### ISSUE TITLE
CMake configuration file issues

### ISSUE THREAD

**Issue by sharmamm** [nwukie/ChiDG#3]
Unable to access HDF5 high level libraries with CMake 3.6.0 due to a change in the configuration file.  Use CMake 3.4 until fixed.

**Comment by nwukie** [comment]
There was a regression in CMake version 3.6.0 that caused the HDF5 high-level libraries not to be detected. A patch was issued to the developers that addresses the issue, see the link below. It should be present in the next release from kitware(3.6.1). Alternatively, for Mac machines, the current cmake formula includes the patch so simply doing a 'brew install cmake' should update. You may need to update your homebrew so it has the newest formula. Versions 3.4 and 3.5 are both fine.

https://gitlab.kitware.com/cmake/cmake/issues/16190

**Comment by nwukie** [comment]
Checks for sufficient CMake versions have been added.
